
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Acer-Nitro5
 */
public class JEdit extends javax.swing.JFrame {

    IStudentService _iSinhVienService;
    DefaultTableModel _dDefaultTableModel;
    DefaultComboBoxModel _dComboBoxModel;
    Utilities _Utilities;
    List<Student> _list;
    int _count = 0;

    public JEdit() {
        initComponents();
        setResizable(false);//Không cho thay đổi kích thước
        _list = new ArrayList<Student>();
        _iSinhVienService = new StudentService();
        _Utilities = new Utilities();
        cbcNganh();
        cbcGioiTinh();
        txt_EditMaSinhVien.setEnabled(false);
    }

    public List<Student> getListTEMP() {
        return _list;
    }

    void cbcNganh() {
        _dComboBoxModel = new DefaultComboBoxModel();
        _dComboBoxModel.addElement("UDPM.JAVA");
        _dComboBoxModel.addElement("UDPM.NET");
        _dComboBoxModel.addElement("MOB.IOS");
        cbc_EditNganhHoc.setModel(_dComboBoxModel);
    }

    void cbcGioiTinh() {
        _dComboBoxModel = new DefaultComboBoxModel();
        _dComboBoxModel.addElement("Nam");
        _dComboBoxModel.addElement("Nữ");
        _dComboBoxModel.addElement("Không xác định");
        cbc_EditGioiTinh.setModel(_dComboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_EditMaSinhVien = new javax.swing.JTextField();
        txt_EditPhoneNumber = new javax.swing.JTextField();
        txt_editNAME = new javax.swing.JTextField();
        cbc_EditGioiTinh = new javax.swing.JComboBox<>();
        cbc_EditNganhHoc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_NhapID = new javax.swing.JTextField();
        btn_seachID = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seach By ID ver1.0");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Mã Sinh Viên");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Họ tên ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Số điện thoại");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Giới tính");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Ngành học");

        txt_editNAME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_editNAMEMouseExited(evt);
            }
        });

        cbc_EditGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbc_EditNganhHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("ID :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Nhập ID cần tìm vào bên dưới");

        btn_seachID.setFont(new java.awt.Font("UTM Akashi", 1, 12)); // NOI18N
        btn_seachID.setText("Seach ID");
        btn_seachID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seachIDMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("UTM Cookies", 1, 14)); // NOI18N
        jButton1.setText("Save Data");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_NhapID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(btn_seachID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                        .addGap(154, 154, 154))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_EditPhoneNumber)
                                    .addComponent(txt_editNAME)
                                    .addComponent(txt_EditMaSinhVien)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbc_EditGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbc_EditNganhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 104, Short.MAX_VALUE)))))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NhapID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seachID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_editNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_EditMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_EditPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbc_EditNganhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbc_EditGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_seachIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seachIDMouseClicked
        if (txt_NhapID.getText().isBlank() || !_Utilities.checkSo(txt_NhapID.getText())) {
            JOptionPane.showMessageDialog(this, "ID bạn nhập để trống hoặc không phù hợp!");
            return;
        }
        else if (Integer.parseInt(txt_NhapID.getText()) > getMaxID() - 1) {
            JOptionPane.showMessageDialog(this, "ID bạn nhập không tìm thấy !");
            return;
        }

        for (Student x : _list) {
            if (x.getId() == Integer.parseInt(txt_NhapID.getText())) {
                txt_editNAME.setText(x.getTen());//Lấy từ list ra text
                txt_EditMaSinhVien.setText(x.getMsv());
                txt_EditPhoneNumber.setText(x.getSdt());
                cbc_EditNganhHoc.setSelectedItem(x.getNganhHoc() == 1 ? "UDPM.JAVA" : x.getNganhHoc() == 2 ? "UDPM.NET" : "MOB.IOS");
                cbc_EditGioiTinh.setSelectedItem(x.getGioitinh() == 1 ? "Nam" : x.getGioitinh() == 2 ? "Nữ" : "Không xác định");
            }
        }
    }//GEN-LAST:event_btn_seachIDMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        for (Student x : _list) {
            if (x.getId() == Integer.parseInt(txt_NhapID.getText())) {
                x.setTen(txt_editNAME.getText());//Lấy từ text vào list
                x.setMsv(txt_EditMaSinhVien.getText());
                x.setSdt(txt_EditPhoneNumber.getText());
                x.setNganhHoc(cbc_EditNganhHoc.getSelectedItem() == "UDPM.JAVA" ? 1 : cbc_EditNganhHoc.getSelectedItem() == "UDPM.NET" ? 2 : 3);
                x.setGioitinh(cbc_EditGioiTinh.getSelectedItem() == "Nam" ? 1 : cbc_EditGioiTinh.getSelectedItem() == "Nữ" ? 2 : 3);
            }
        }
        for (Student x : _list) {
            _iSinhVienService.getlstStudents().add(x);
        }
        JOptionPane.showMessageDialog(this, "Sửa thành công ! Bấm LOAD để cập nhật lại !");
//        System.out.println(_iSinhVienService.getlstStudents().size());
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked


    private void txt_editNAMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_editNAMEMouseExited
        if (txt_editNAME.getText().isBlank()) {
            txt_EditMaSinhVien.setText("");
            return;
        }
        String name = _Utilities.convertFullName(txt_editNAME.getText().toLowerCase());
        txt_editNAME.setText(name);
        txt_EditMaSinhVien.setText(_Utilities.msvFpoly(name, getMaxID(), 0));
    }//GEN-LAST:event_txt_editNAMEMouseExited
    public int getMaxID() {
        if (_list.isEmpty()) {
            return 1;
        }
        int max = _list.get(0).getId();
        for (Student x : _list) {
            if (max < x.getId()) {
                max = x.getId();
            }
        }
        return max + 1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_seachID;
    private javax.swing.JComboBox<String> cbc_EditGioiTinh;
    private javax.swing.JComboBox<String> cbc_EditNganhHoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_EditMaSinhVien;
    private javax.swing.JTextField txt_EditPhoneNumber;
    private javax.swing.JTextField txt_NhapID;
    private javax.swing.JTextField txt_editNAME;
    // End of variables declaration//GEN-END:variables
}
