
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyễn Viết Dũng
 */
public class Main extends javax.swing.JFrame {

    IStudentService _iSinhVienService;
    DefaultTableModel _dDefaultTableModel;
    DefaultComboBoxModel _dComboBoxModel;
    Utilities _Utilities;

    public Main() {
        initComponents();
        setResizable(false);//Không cho thay đổi kích thước
        _iSinhVienService = new StudentService();
        _Utilities = new Utilities();
        cbcNganh();
        cbcGioiTinh();
        lbl_FBIwarning.setVisible(false);
        txt_Id.setEnabled(false);//Làm mờ ô textbox và không cho can thiệp vào dữ liệu
        txt_MaSV.setEnabled(false);
        getMAXID();//Tự động nhảy ID trên GUI
    }

    void loadData(List<Student> data) {
        _dDefaultTableModel = (DefaultTableModel) tbl_SinhVien.getModel();
        _dDefaultTableModel.setRowCount(0);
        int stt = 1;
        for (Student x : data) {
            _dDefaultTableModel.addRow(new Object[]{stt++, x.getId(), x.getTen(), x.getSdt(), x.getMsv(), x.getNganhHoc() == 1 ? "UDPM.JAVA" : x.getNganhHoc() == 2 ? "UDPM.NET" : "MOB.IOS", x.getGioitinh() == 1 ? "Nam" : x.getGioitinh() == 2 ? "Nữ" : "Không xác định"});
        }
        getMAXID();
    }

    void getMAXID() {
        txt_Id.setText(String.valueOf(_iSinhVienService.getMaxID()));
    }

    Student getDataGui() {//Trả về 1 đối tượng lấy từ Control
        //Nếu không code được đoạn này thì khai báo 1 Student xong rồi chám từng thuộc tính gắn cho control
        return new Student(
                Integer.parseInt(txt_Id.getText()),
                txt_FullName.getText(),
                txt_PhoneNumber.getText(),
                txt_MaSV.getText(),
                (cbc_NganhHoc.getSelectedItem() == "UDPM.JAVA" ? 1 : cbc_NganhHoc.getSelectedItem() == "UDPM.NET" ? 2 : 3),
                (cbc_GioiTinh.getSelectedItem() == "Nam" ? 1 : cbc_GioiTinh.getSelectedItem() == "Nữ" ? 2 : 3)
        );
    }

    void cbcNganh() {
        _dComboBoxModel = new DefaultComboBoxModel();
        _dComboBoxModel.addElement("UDPM.JAVA");
        _dComboBoxModel.addElement("UDPM.NET");
        _dComboBoxModel.addElement("MOB.IOS");
        cbc_NganhHoc.setModel(_dComboBoxModel);
    }

    void cbcGioiTinh() {
        _dComboBoxModel = new DefaultComboBoxModel();
        _dComboBoxModel.addElement("Nam");
        _dComboBoxModel.addElement("Nữ");
        _dComboBoxModel.addElement("Không xác định");
        cbc_GioiTinh.setModel(_dComboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_FBIwarning = new javax.swing.JLabel();
        lbl_SearchIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        txt_FullName = new javax.swing.JTextField();
        txt_PhoneNumber = new javax.swing.JTextField();
        txt_MaSV = new javax.swing.JTextField();
        btn_Edit = new javax.swing.JButton();
        btn_Del = new javax.swing.JButton();
        btn_FakeData = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();
        txt_TimKiem = new javax.swing.JTextField();
        cbc_GioiTinh = new javax.swing.JComboBox<>();
        cbc_NganhHoc = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_SinhVien = new javax.swing.JTable();
        btn_LOADING = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ SINH VIÊN 2022 ver1.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_FBIwarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_FBIwarning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/warning.png"))); // NOI18N
        getContentPane().add(lbl_FBIwarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 40, 40));

        lbl_SearchIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        lbl_SearchIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_SearchIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SearchIconMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_SearchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 50, 50));

        jLabel1.setBackground(new java.awt.Color(51, 255, 51));
        jLabel1.setFont(new java.awt.Font("UTM Conestoga", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("QUẢN LÝ SINH VIÊN 2022");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 0, -1, 67));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 100, 42, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("FULL NAME :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 158, -1, 39));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("PHONE NUMBER :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 217, -1, 37));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 255));
        jLabel5.setText("CODE :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 100, 91, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setText("MAJORS :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 158, -1, 41));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 255));
        jLabel7.setText("SEX :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 217, 91, -1));

        txt_Id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 100, 106, 40));

        txt_FullName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_FullName.setText("Enter your Full Name");
        txt_FullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_FullNameFocusLost(evt);
            }
        });
        txt_FullName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_FullNameMouseExited(evt);
            }
        });
        getContentPane().add(txt_FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 159, 374, 40));

        txt_PhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_PhoneNumber.setText("Enter your Phone Number");
        txt_PhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PhoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PhoneNumberFocusLost(evt);
            }
        });
        txt_PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txt_PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 217, 326, 37));

        txt_MaSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_MaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 100, 265, 40));

        btn_Edit.setBackground(new java.awt.Color(255, 153, 51));
        btn_Edit.setFont(new java.awt.Font("UTM Centur", 3, 10)); // NOI18N
        btn_Edit.setForeground(new java.awt.Color(153, 0, 153));
        btn_Edit.setText("EDIT");
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 272, 60, 40));

        btn_Del.setBackground(new java.awt.Color(255, 51, 0));
        btn_Del.setFont(new java.awt.Font("UTM Centur", 3, 10)); // NOI18N
        btn_Del.setForeground(new java.awt.Color(153, 0, 153));
        btn_Del.setText("DEL");
        btn_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Del, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 272, 60, 40));

        btn_FakeData.setBackground(new java.awt.Color(204, 204, 255));
        btn_FakeData.setFont(new java.awt.Font("UTM Centur", 3, 10)); // NOI18N
        btn_FakeData.setForeground(new java.awt.Color(153, 0, 153));
        btn_FakeData.setText("FAKE DATA");
        btn_FakeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FakeDataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_FakeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 272, 100, 40));

        btn_Add.setBackground(new java.awt.Color(153, 255, 153));
        btn_Add.setFont(new java.awt.Font("UTM Centur", 3, 10)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(153, 0, 153));
        btn_Add.setText("ADD");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 272, 60, 40));

        txt_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TimKiem.setForeground(new java.awt.Color(153, 153, 153));
        txt_TimKiem.setText("Enter a name or code to search...");
        txt_TimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_TimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_TimKiemFocusLost(evt);
            }
        });
        getContentPane().add(txt_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 274, 267, 46));

        cbc_GioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbc_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbc_GioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbc_GioiTinhActionPerformed(evt);
            }
        });
        getContentPane().add(cbc_GioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 217, 267, 37));

        cbc_NganhHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbc_NganhHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbc_NganhHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbc_NganhHocActionPerformed(evt);
            }
        });
        getContentPane().add(cbc_NganhHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 158, 265, 41));

        tbl_SinhVien.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tbl_SinhVien.setForeground(new java.awt.Color(51, 153, 0));
        tbl_SinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID", "Họ Và Tên", "SĐT", "MSV", "Ngành Học", "Giới Tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_SinhVien);
        if (tbl_SinhVien.getColumnModel().getColumnCount() > 0) {
            tbl_SinhVien.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbl_SinhVien.getColumnModel().getColumn(1).setPreferredWidth(5);
            tbl_SinhVien.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 356, 892, 260));

        btn_LOADING.setBackground(new java.awt.Color(204, 204, 0));
        btn_LOADING.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btn_LOADING.setText("LOAD");
        btn_LOADING.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LOADINGMouseClicked(evt);
            }
        });
        btn_LOADING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LOADINGActionPerformed(evt);
            }
        });
        getContentPane().add(btn_LOADING, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 273, 73, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3312684.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbc_GioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbc_GioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbc_GioiTinhActionPerformed

    private void cbc_NganhHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbc_NganhHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbc_NganhHocActionPerformed

    private void btn_FakeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FakeDataActionPerformed
        _iSinhVienService.fake5Data();
        loadData(_iSinhVienService.getlstStudents());
    }//GEN-LAST:event_btn_FakeDataActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        JOptionPane.showMessageDialog(this, _iSinhVienService.add(getDataGui()));
        loadData(_iSinhVienService.getlstStudents());
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelActionPerformed
        if (_iSinhVienService.getlstStudents().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách trống");
            return;
        }
        int index = tbl_SinhVien.getSelectedRow();//Lấy được vị trí người dùng bấm
        //Chưa làm hành động bấm vào load lên trên
        JOptionPane.showMessageDialog(this, _iSinhVienService.delete(String.valueOf(_iSinhVienService.getlstStudents().get(index).getId())));
        loadData(_iSinhVienService.getlstStudents());
    }//GEN-LAST:event_btn_DelActionPerformed

    private void txt_FullNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_FullNameMouseExited
        if (txt_FullName.getText().isBlank()) {
            txt_MaSV.setText("");
            return;
        }
        else if (_Utilities.checkSo(txt_FullName.getText())) {
            txt_FullName.setForeground(Color.red);
            lbl_FBIwarning.setVisible(true);
            btn_Add.setEnabled(false);
            return;
        }
        txt_FullName.setForeground(Color.black);
        lbl_FBIwarning.setVisible(false);
        btn_Add.setEnabled(true);
        String name = _Utilities.convertFullName(txt_FullName.getText().toLowerCase());
        txt_FullName.setText(name);
        txt_MaSV.setText(_Utilities.msvFpoly(name, _iSinhVienService.getMaxID(), 0));
    }//GEN-LAST:event_txt_FullNameMouseExited

    private void btn_LOADINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LOADINGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LOADINGActionPerformed

    private void btn_LOADINGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LOADINGMouseClicked
        loadData(_iSinhVienService.getlstStudents());
    }//GEN-LAST:event_btn_LOADINGMouseClicked

    private void btn_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseClicked
        JEdit editfull = new JEdit();
        editfull.setLocationRelativeTo(null);
        editfull.setVisible(true);
        editfull.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        for (Student x : _iSinhVienService.getlstStudents()) {
            editfull.getListTEMP().add(x);
        }
    }//GEN-LAST:event_btn_EditMouseClicked

    private void txt_TimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TimKiemFocusGained
        if (txt_TimKiem.getText().equals("Enter a name or code to search...")) {
            txt_TimKiem.setText("");
            txt_TimKiem.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_TimKiemFocusGained

    private void txt_TimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TimKiemFocusLost
        if (txt_TimKiem.getText().equals("")) {
            txt_TimKiem.setText("Enter a name or code to search...");
            txt_TimKiem.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_TimKiemFocusLost

    private void txt_FullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FullNameFocusGained
        // TODO add your handling code here:
        if (txt_FullName.getText().equals("Enter your Full Name")) {
            txt_FullName.setText("");
            txt_FullName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_FullNameFocusGained

    private void txt_FullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FullNameFocusLost
        if (txt_FullName.getText().equals("")) {
            txt_FullName.setText("Enter your Full Name");
            txt_FullName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_FullNameFocusLost

    private void txt_PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhoneNumberActionPerformed

    private void txt_PhoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PhoneNumberFocusGained
        if (txt_PhoneNumber.getText().equals("Enter your Phone Number")) {
            txt_PhoneNumber.setText("");
            txt_PhoneNumber.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_PhoneNumberFocusGained

    private void txt_PhoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PhoneNumberFocusLost
        if (txt_PhoneNumber.getText().equals("")) {
            txt_PhoneNumber.setText("Enter your Phone Number");
            txt_PhoneNumber.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_PhoneNumberFocusLost

    private void lbl_SearchIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SearchIconMouseClicked
      loadData(_iSinhVienService.find(txt_TimKiem.getText()));
    }//GEN-LAST:event_lbl_SearchIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main mn = new Main();
                mn.setLocationRelativeTo(null);
                mn.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Del;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_FakeData;
    private javax.swing.JButton btn_LOADING;
    private javax.swing.JComboBox<String> cbc_GioiTinh;
    private javax.swing.JComboBox<String> cbc_NganhHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_FBIwarning;
    private javax.swing.JLabel lbl_SearchIcon;
    private javax.swing.JTable tbl_SinhVien;
    private javax.swing.JTextField txt_FullName;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_MaSV;
    private javax.swing.JTextField txt_PhoneNumber;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
